services:
  database:
    image: postgres:13.22-alpine3.22
    container_name: pulse-db
    restart: always
    ports:
      - '5432:5432'
    env_file: .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - postgres

  redis:
    image: redis:alpine3.22
    container_name: pulse-redis
    restart: always
    ports:
      - '6379:6379'
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: always
    ports:
      - '8080:8080'
    env_file: .env.dev
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    depends_on:
      database:
        condition: service_healthy
volumes:
  pgdata:
  evolution_store:
  evolution_instances: